version: '3'

services:
  jvm_compose:
    image: quarkus/bitcoin-jvm:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://postgres_bitcoin:5432/postgres
    networks:
      - postgres-compose-network
    ports:
      - 8080:8080
    depends_on:
      - postgres_compose

  postgres_compose:
    image: postgres:12.2
    environment:
      POSTGRES_USER: bitcoin
      POSTGRES_PASSWORD: bitcoin
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dcatapan@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge